/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Editor: typeof import('primevue/editor')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Generator: typeof import('./src/components/base/Generator.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/layouts/Layout.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('primevue/slider')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
}
